### PR TITLE
Testing and Popout is working with exit button

### PR DESCRIPTION
**Pull request by michaelrtobias**

### CODE REVIEW

**Comment by michaelrtobias** [comment]
@jasondstrunk

**Review by jasondstrunk — APPROVED** [review]
Client side tests look good. Your Exit, Popout, and BigImage components can probably be stateless "dummy" components instead of classes. Not sure if that's a big deal or not, but that's how we've done it with other projects.

**Comment by michaelrtobias** [comment]
There is still a lot of event handling to be done in the popout so a lot of those components are going to need to be classes. I was just setting it up for todays work/changes

**Comment by jasondstrunk** [comment]
Oh got it. Right on.

**Pull request merged**
